### ISSUE TITLE
Local development setup

### ISSUE THREAD

**Issue by mrfambo** [parcelvoy/platform#269]
Hi, 

Great work. I would love to contribute but it is very hard for me to set up the local development environment. If we look at the API, it is running on `PORT` env variable mentioned in `/config/env.ts` file and it is the same environment being used by the React App. I am assuming we are running `npm start` to boot the application using lerna.

What am I missing here? If I change the API to serve on a different port then i am having issues where you are setting up redirects after basic authentication.

What is your flow of running it locally? It will be a great help if you could guide me on it.

Once again, great work.

**Comment by pushchris** [comment]
Hello! Great callouts all around. For a dev setup you need to run the UI on one port and the API on another and then have the UI proxy requests to the API. So for example if you wanted to access the UI through port `3000` you could set `PORT` in the API env to be `3001` so it is on a different port and then set:
```
REACT_APP_API_BASE_URL=http://localhost:3000/api
REACT_APP_PROXY_URL=http://localhost:3001
```
On the react app so that it proxies the API requests to port `3001`.

I created some example env files for each platform that should hopefully give some context as to what you need to set at a bare minimum. Please let me know if you have any further difficulties!

https://github.com/parcelvoy/platform/pull/270

**Comment by mrfambo** [comment]
Thank you so much @pushchris. Probably that was the part i missed that each app inside ‘/apps’ can have its own ‘.env’ file.

I will try and get back to you. Once again, thank you so so much.

**Comment by mrfambo** [comment]
Worked like a charm. I will add one more thing. 
Don't forget to add `BASE_URL=http://localhost:3000` in `apps/platform/.env` so that redirects points out to correct domain.
