### ISSUE TITLE
We need a better documentation

### ISSUE THREAD

**Issue by alvarogabrielgomez** [parcelvoy/platform#364]
The documentation about the use of journeys is not the best. We need examples, templates, how exactly use each tool. In the documentations says that use handlebars but when I try to use it does not work, so how exactly you implement handlebars templates?... Same with email campaings, the editor does not have integration with the variables to populate the email with user and event data. We dont have examples of how to do it and when you use the {{ user.email }} squeme dont work as well. I'm very lost using this. We need examples of how exactly do the things

**Comment by pushchris** [comment]
@alvarogabrielgomez it sounds like you might have a different problem going on because accessing the user email like you have listed should work. [There is a section on accessing variables ](https://docs.parcelvoy.com/how-to/campaigns/templates#variables) and all of the functions available to be used in handlebars in the documentation. I just validated on my end that it works properly for both visual and code based email templates. Could you please provide an example of a template where it is not working? Screenshots could additionally be helpful.

As for documentation on journeys, we will look into providing user guides in the future since it sounds like that is more what you are looking for.
