### ISSUE TITLE
Is there a way to use relative date values on Rules?

### ISSUE THREAD

**Issue by davidgalarza** [parcelvoy/platform#367]
For example we want to create a list of the users that were created in the last week. For that we can set the dates, but is interesting use dynamically the values of today and seven days ago.
<img width="621" alt="Screenshot 2024-03-01 at 11 03 07 AM" src="https://github.com/parcelvoy/platform/assets/20847597/aef380ef-f5db-4a33-ac63-26f562d394a1">

**Comment by pushchris** [comment]
You are able to use Handlebars in those fields to calculate different values. For dates specifically we have a number of [functions you can use](https://docs.parcelvoy.com/how-to/campaigns/templates#dates). That said, lists do not re-evaluate based on time changing only when user properties and events changing. So if for example you want a list of only users that signed up in the last seven days that is not possible with lists as users older than seven days would still stay in the lists since their membership is not re-evaluated as time progresses. 

A better fit for this kind of behavior (or anything being guided by time) would be journeys where you can specify gaps between time as delays for example. You could setup an entrance then a seven day delay and then send an email, etc. Rule evaluation inside of journeys is also dynamic since it gets evaluated at runtime when a user reaches that step instead of once for entry.

**Comment by pushchris** [comment]
Closing for now, please feel free to reopen if you have additional questions or issues!
