### ISSUE TITLE
List length is not correct

### ISSUE THREAD

**Issue by mattes3** [parcelvoy/platform#438]
Today, I imported 1055 people into a static list, in 22 files of around 50 people each. The `user_created` events triggered a journey and Parcelvoy correctly sent the first 1055 emails. Happy about this!

When I look at the static list, it says that it contains only 891 people:
<img width="884" alt="CleanShot 2024-04-07 at 20 34 58@2x" src="https://github.com/parcelvoy/platform/assets/2496674/0b8146e3-3935-4ff1-a432-422ae4208f13">

However, when I look into the database, all 1055 people are in the `users` table:
<img width="606" alt="CleanShot 2024-04-07 at 20 38 20@2x" src="https://github.com/parcelvoy/platform/assets/2496674/8c284eb2-97e5-4039-bad3-ae9aade96625">

What gives?

**Comment by pushchris** [comment]
Ok, so this issue looks like it's related to how we internally were counting users in the list. It runs in chunks over time to prevent having to run full counting queries over the table and should be self-healing but because the table only has second accuracy it was missing some rows. This should be resolved #439, you may need to just re-upload one of your lists and the count should fix itself.
