### ISSUE TITLE
The `topic` field on the `fr` template is missing and is required

### ISSUE THREAD

**Issue by reaper** [parcelvoy/platform#472]
Hello,

I run parcelvoy on docker and configured the APN/Firebase provider, but when I try to start a campaign, configured with a title, body and a deeplink, I reproduce the following issue with my uniq matched user:

```json
{
  "name": "push_failed",
  "error": {
    "error": "The `topic` field on the `fr` template is missing and is required.",
    "status": "error"
  },
  "channel": "push",
  "campaign_id": 2,
  "template_id": 2,
  "campaign_name": "Test push notifications",
  "campaign_type": "blast",
  "subscription_id": 3,
  "created_at": "2024-06-25T12:51:02.000Z"
}
```

I cannot find any field with this name or the ability to add a topic key in a payload before sending it.

Same for the english locale: 
```
The `topic` field on the `en` template is missing and is required.
```

Can you advise please?

**Comment by pushchris** [comment]
@reaper please upgrade to the latest version and give it another go. Looks like there were a number of things going on with notifications. Unfortunately you are also going to have to update the FCM settings on your push notifications provider (if you are trying to send to an Android device) since Google has decided to EOL the endpoints we were using to send notifications.

**Comment by reaper** [comment]
Thanks for the answer @pushchris. I no longer reproduce the topic issue but I now catch another. I created an issue: https://github.com/parcelvoy/platform/issues/474.
