### ISSUE TITLE
Push message open event not getting tracked

### ISSUE THREAD

**Issue by tanmay-predisai** [parcelvoy/platform#515]
Hello, We started sending push notifications to users in a journey - Thank you for the new release :)  

Here are some observations:

1. Even if a user clicks on a notification, it does not register a "push opened" event. In emails, the "email open" event gets registered by default. Is this by design?
2. If a users blocks push messages, we see the "notifications_disabled" event. However, the user's subscription on the "Push" channel does not get unsubscribed. Should this be done by default or we should make a new journey to be triggered on the "notifications_disabled" event? 

Thank you for your help!

**Comment by pushchris** [comment]
1. You can see a bit more discussion on this topic here: https://github.com/parcelvoy/platform/issues/499 but the short answer is it isn't currently implemented and requires some considerations
2. This is correct, a user can have more than one total device, it is not a 1:1 relationship between the two and we shouldn't assume that they want the subscription channel disabled just because of an uninstall for example. In the case of emails, an unsubscribe is literally disabling that channel but the user also can't have multiple registered email addresses so the situation isn't identical.
